[init : remove] Removing all files from /workspace/source ...

[clone : clone] + '[' false '=' true ]
[clone : clone] + '[' false '=' true ]
[clone : clone] + '[' false '=' true ]
[clone : clone] + CHECKOUT_DIR=/workspace/output/
[clone : clone] + '[' true '=' true ]
[clone : clone] + cleandir
[clone : clone] + '[' -d /workspace/output/ ]
[clone : clone] + rm -rf '/workspace/output//*'
[clone : clone] + rm -rf '/workspace/output//.[!.]*'
[clone : clone] + rm -rf '/workspace/output//..?*'
[clone : clone] + test -z 
[clone : clone] + test -z 
[clone : clone] + test -z 
[clone : clone] + git config --global --add safe.directory /workspace/output
[clone : clone] + /ko-app/git-init '-url=https://github.com/AlexMGH/devops-capstone-project.git' '-revision=main' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
[clone : clone] {"level":"info","ts":1678891304.7153237,"caller":"git/git.go:176","msg":"Successfully cloned https://github.com/AlexMGH/devops-capstone-project.git @ bd53641428d1b3ad1f3bc75e34c880cefed1f90d (grafted, HEAD, origin/main) in path /workspace/output/"}
[clone : clone] {"level":"info","ts":1678891304.7775524,"caller":"git/git.go:215","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
[clone : clone] + cd /workspace/output/
[clone : clone] + git rev-parse HEAD
[clone : clone] + RESULT_SHA=bd53641428d1b3ad1f3bc75e34c880cefed1f90d
[clone : clone] + EXIT_CODE=0
[clone : clone] + '[' 0 '!=' 0 ]
[clone : clone] + git log -1 '--pretty=%ct'
[clone : clone] + RESULT_COMMITTER_DATE=1678890811
[clone : clone] + printf '%s' 1678890811
[clone : clone] + printf '%s' bd53641428d1b3ad1f3bc75e34c880cefed1f90d
[clone : clone] + printf '%s' https://github.com/AlexMGH/devops-capstone-project.git

[lint : flake8] Collecting Werkzeug>=2.1.2
[lint : flake8]   Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 KB 63.6 MB/s eta 0:00:00
[lint : flake8] Collecting Flask>=2.1.2
[lint : flake8]   Downloading Flask-2.2.3-py3-none-any.whl (101 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 KB 57.0 MB/s eta 0:00:00
[lint : flake8] Collecting Flask-SQLAlchemy==2.5.1
[lint : flake8]   Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
[lint : flake8] Collecting Flask-Cors==3.0.10
[lint : flake8]   Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
[lint : flake8] Collecting Flask-Talisman==1.0.0
[lint : flake8]   Downloading flask_talisman-1.0.0-py2.py3-none-any.whl (18 kB)
[lint : flake8] Collecting psycopg2-binary>=2.9.3
[lint : flake8]   Downloading psycopg2_binary-2.9.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 40.5 MB/s eta 0:00:00
[lint : flake8] Collecting python-dotenv>=0.20.0
[lint : flake8]   Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
[lint : flake8] Collecting gunicorn>=20.1.0
[lint : flake8]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 41.5 MB/s eta 0:00:00
[lint : flake8] Collecting honcho>=1.1.0
[lint : flake8]   Downloading honcho-1.1.0-py2.py3-none-any.whl (21 kB)
[lint : flake8] Collecting pylint>=2.14.0
[lint : flake8]   Downloading pylint-2.17.0-py3-none-any.whl (535 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 535.4/535.4 KB 100.8 MB/s eta 0:00:00
[lint : flake8] Collecting flake8>=4.0.1
[lint : flake8]   Downloading flake8-6.0.0-py2.py3-none-any.whl (57 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 KB 29.1 MB/s eta 0:00:00
[lint : flake8] Collecting black>=22.3.0
[lint : flake8]   Downloading black-23.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 84.0 MB/s eta 0:00:00
[lint : flake8] Collecting nose>=1.3.7
[lint : flake8]   Downloading nose-1.3.7-py3-none-any.whl (154 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 KB 39.9 MB/s eta 0:00:00
[lint : flake8] Collecting pinocchio>=0.4.3
[lint : flake8]   Downloading pinocchio-0.4.3-py3-none-any.whl (12 kB)
[lint : flake8] Collecting factory-boy>=2.12.0
[lint : flake8]   Downloading factory_boy-3.2.1-py2.py3-none-any.whl (35 kB)
[lint : flake8] Collecting coverage>=6.3.2
[lint : flake8]   Downloading coverage-7.2.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (226 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.9/226.9 KB 4.3 MB/s eta 0:00:00
[lint : flake8] Collecting codecov>=2.1.12
[lint : flake8]   Downloading codecov-2.1.12-py2.py3-none-any.whl (16 kB)
[lint : flake8] Collecting httpie>=3.2.1
[lint : flake8]   Downloading httpie-3.2.1-py3-none-any.whl (124 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 KB 62.9 MB/s eta 0:00:00
[lint : flake8] Collecting SQLAlchemy>=0.8.0
[lint : flake8]   Downloading SQLAlchemy-2.0.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 41.1 MB/s eta 0:00:00
[lint : flake8] Collecting Six
[lint : flake8]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[lint : flake8] Collecting MarkupSafe>=2.1.1
[lint : flake8]   Downloading MarkupSafe-2.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
[lint : flake8] Collecting importlib-metadata>=3.6.0
[lint : flake8]   Downloading importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
[lint : flake8] Collecting Jinja2>=3.0
[lint : flake8]   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 45.2 MB/s eta 0:00:00
[lint : flake8] Collecting click>=8.0
[lint : flake8]   Downloading click-8.1.3-py3-none-any.whl (96 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 44.8 MB/s eta 0:00:00
[lint : flake8] Collecting itsdangerous>=2.0
[lint : flake8]   Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
[lint : flake8] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn>=20.1.0->-r requirements.txt (line 13)) (58.1.0)
[lint : flake8] Collecting typing-extensions>=3.10.0
[lint : flake8]   Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[lint : flake8] Collecting tomlkit>=0.10.1
[lint : flake8]   Downloading tomlkit-0.11.6-py3-none-any.whl (35 kB)
[lint : flake8] Collecting tomli>=1.1.0
[lint : flake8]   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
[lint : flake8] Collecting mccabe<0.8,>=0.6
[lint : flake8]   Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
[lint : flake8] Collecting astroid<=2.17.0-dev0,>=2.15.0
[lint : flake8]   Downloading astroid-2.15.0-py3-none-any.whl (277 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.7/277.7 KB 91.6 MB/s eta 0:00:00
[lint : flake8] Collecting platformdirs>=2.2.0
[lint : flake8]   Downloading platformdirs-3.1.1-py3-none-any.whl (14 kB)
[lint : flake8] Collecting isort<6,>=4.2.5
[lint : flake8]   Downloading isort-5.12.0-py3-none-any.whl (91 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 KB 48.7 MB/s eta 0:00:00
[lint : flake8] Collecting dill>=0.2
[lint : flake8]   Downloading dill-0.3.6-py3-none-any.whl (110 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 55.5 MB/s eta 0:00:00
[lint : flake8] Collecting pyflakes<3.1.0,>=3.0.0
[lint : flake8]   Downloading pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 37.3 MB/s eta 0:00:00
[lint : flake8] Collecting pycodestyle<2.11.0,>=2.10.0
[lint : flake8]   Downloading pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 KB 19.7 MB/s eta 0:00:00
[lint : flake8] Collecting mypy-extensions>=0.4.3
[lint : flake8]   Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
[lint : flake8] Collecting pathspec>=0.9.0
[lint : flake8]   Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
[lint : flake8] Collecting packaging>=22.0
[lint : flake8]   Downloading packaging-23.0-py3-none-any.whl (42 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 25.0 MB/s eta 0:00:00
[lint : flake8] Collecting colorama
[lint : flake8]   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
[lint : flake8] Collecting Faker>=0.7.0
[lint : flake8]   Downloading Faker-17.6.0-py3-none-any.whl (1.7 MB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 128.2 MB/s eta 0:00:00
[lint : flake8] Collecting requests>=2.7.9
[lint : flake8]   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 35.9 MB/s eta 0:00:00
[lint : flake8] Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (from httpie>=3.2.1->-r requirements.txt (line 31)) (22.0.4)
[lint : flake8] Collecting Pygments>=2.5.2
[lint : flake8]   Downloading Pygments-2.14.0-py3-none-any.whl (1.1 MB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 125.7 MB/s eta 0:00:00
[lint : flake8] Collecting defusedxml>=0.6.0
[lint : flake8]   Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
[lint : flake8] Collecting requests-toolbelt>=0.9.1
[lint : flake8]   Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 KB 28.9 MB/s eta 0:00:00
[lint : flake8] Collecting rich>=9.10.0
[lint : flake8]   Downloading rich-13.3.2-py3-none-any.whl (238 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.7/238.7 KB 90.7 MB/s eta 0:00:00
[lint : flake8] Collecting multidict>=4.7.0
[lint : flake8]   Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 55.0 MB/s eta 0:00:00
[lint : flake8] Collecting charset-normalizer>=2.0.0
[lint : flake8]   Downloading charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 82.6 MB/s eta 0:00:00
[lint : flake8] Collecting lazy-object-proxy>=1.4.0
[lint : flake8]   Downloading lazy_object_proxy-1.9.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 KB 33.4 MB/s eta 0:00:00
[lint : flake8] Collecting wrapt<2,>=1.11
[lint : flake8]   Downloading wrapt-1.15.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 KB 40.5 MB/s eta 0:00:00
[lint : flake8] Collecting python-dateutil>=2.4
[lint : flake8]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 88.9 MB/s eta 0:00:00
[lint : flake8] Collecting zipp>=0.5
[lint : flake8]   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
[lint : flake8] Collecting urllib3<1.27,>=1.21.1
[lint : flake8]   Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 KB 48.6 MB/s eta 0:00:00
[lint : flake8] Collecting certifi>=2017.4.17
[lint : flake8]   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 KB 3.0 MB/s eta 0:00:00
[lint : flake8] Collecting idna<4,>=2.5
[lint : flake8]   Downloading idna-3.4-py3-none-any.whl (61 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 27.1 MB/s eta 0:00:00
[lint : flake8] Collecting PySocks!=1.5.7,>=1.5.6
[lint : flake8]   Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
[lint : flake8] Collecting markdown-it-py<3.0.0,>=2.2.0
[lint : flake8]   Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 42.1 MB/s eta 0:00:00
[lint : flake8] Collecting greenlet!=0.4.17
[lint : flake8]   Downloading greenlet-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (610 kB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 KB 114.6 MB/s eta 0:00:00
[lint : flake8] Collecting mdurl~=0.1
[lint : flake8]   Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
[lint : flake8] Installing collected packages: nose, honcho, Flask-Talisman, zipp, wrapt, urllib3, typing-extensions, tomlkit, tomli, Six, python-dotenv, PySocks, Pygments, pyflakes, pycodestyle, psycopg2-binary, platformdirs, pathspec, packaging, mypy-extensions, multidict, mdurl, mccabe, MarkupSafe, lazy-object-proxy, itsdangerous, isort, idna, gunicorn, greenlet, dill, defusedxml, coverage, colorama, click, charset-normalizer, certifi, Werkzeug, SQLAlchemy, requests, python-dateutil, pinocchio, markdown-it-py, Jinja2, importlib-metadata, flake8, black, astroid, rich, requests-toolbelt, pylint, Flask, Faker, codecov, httpie, Flask-SQLAlchemy, Flask-Cors, factory-boy
[lint : flake8] Successfully installed Faker-17.6.0 Flask-2.2.3 Flask-Cors-3.0.10 Flask-SQLAlchemy-2.5.1 Flask-Talisman-1.0.0 Jinja2-3.1.2 MarkupSafe-2.1.2 PySocks-1.7.1 Pygments-2.14.0 SQLAlchemy-2.0.6 Six-1.16.0 Werkzeug-2.2.3 astroid-2.15.0 black-23.1.0 certifi-2022.12.7 charset-normalizer-3.1.0 click-8.1.3 codecov-2.1.12 colorama-0.4.6 coverage-7.2.1 defusedxml-0.7.1 dill-0.3.6 factory-boy-3.2.1 flake8-6.0.0 greenlet-2.0.2 gunicorn-20.1.0 honcho-1.1.0 httpie-3.2.1 idna-3.4 importlib-metadata-6.0.0 isort-5.12.0 itsdangerous-2.1.2 lazy-object-proxy-1.9.0 markdown-it-py-2.2.0 mccabe-0.7.0 mdurl-0.1.2 multidict-6.0.4 mypy-extensions-1.0.0 nose-1.3.7 packaging-23.0 pathspec-0.11.1 pinocchio-0.4.3 platformdirs-3.1.1 psycopg2-binary-2.9.5 pycodestyle-2.10.0 pyflakes-3.0.1 pylint-2.17.0 python-dateutil-2.8.2 python-dotenv-1.0.0 requests-2.28.2 requests-toolbelt-0.10.1 rich-13.3.2 tomli-2.0.1 tomlkit-0.11.6 typing-extensions-4.5.0 urllib3-1.26.15 wrapt-1.15.0 zipp-3.15.0
[lint : flake8] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[lint : flake8] WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
[lint : flake8] You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[lint : flake8] ./tests/test_routes.py:192:1: W293 blank line contains whitespace
[lint : flake8] 1     W293 blank line contains whitespace
[lint : flake8] 1

[tests : nosetests] ***** Installing dependencies *****
[tests : nosetests] Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (22.0.4)
[tests : nosetests] Collecting pip
[tests : nosetests]   Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
[tests : nosetests]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 39.6 MB/s eta 0:00:00
[tests : nosetests] Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (0.38.4)
[tests : nosetests] Collecting wheel
[tests : nosetests]   Downloading wheel-0.40.0-py3-none-any.whl (64 kB)
[tests : nosetests]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 KB 32.0 MB/s eta 0:00:00
[tests : nosetests] Installing collected packages: wheel, pip
[tests : nosetests]   Attempting uninstall: wheel
[tests : nosetests]     Found existing installation: wheel 0.38.4
[tests : nosetests]     Uninstalling wheel-0.38.4:
[tests : nosetests]       Successfully uninstalled wheel-0.38.4
[tests : nosetests]   Attempting uninstall: pip
[tests : nosetests]     Found existing installation: pip 22.0.4
[tests : nosetests]     Uninstalling pip-22.0.4:
[tests : nosetests]       Successfully uninstalled pip-22.0.4
[tests : nosetests] Successfully installed pip-23.0.1 wheel-0.40.0
[tests : nosetests] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[tests : nosetests] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[tests : nosetests] ***** Running nosetests with: -v --with-spec --spec-color
[tests : nosetests] nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
[tests : nosetests] nose.plugins.cover: INFO: Coverage report will include only packages: ['service']
[tests : nosetests] 
[tests : nosetests] Unloadable or unexecutable test.
[tests : nosetests] 
[tests : nosetests]     A Failure case is placed in a test suite to indicate the presence of a
[tests : nosetests]     test that could not be loaded or executed. A common example is a test
[tests : nosetests]     module that fails to import.
[tests : nosetests]     
[tests : nosetests]     
[tests : nosetests] [1;31m- runTest (ERROR)[1;0m
[tests : nosetests] [1;31m- runTest (ERROR)[1;0m
[tests : nosetests] [1;31m- runTest (ERROR)[1;0m
[tests : nosetests] [1;31m- runTest (ERROR)[1;0m
[tests : nosetests] 
[tests : nosetests] ======================================================================
[tests : nosetests] ERROR: Failure: AttributeError (module 'sqlalchemy' has no attribute '__all__')
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Traceback (most recent call last):
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
[tests : nosetests]     raise self.exc_val.with_traceback(self.tb)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
[tests : nosetests]     module = self.importer.importFromPath(
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
[tests : nosetests]     return self.importFromDir(dir_path, fqname)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
[tests : nosetests]     mod = load_module(part_fqname, fh, filename, desc)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 244, in load_module
[tests : nosetests]     return load_package(name, filename)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 216, in load_package
[tests : nosetests]     return _load(spec)
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 711, in _load
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[tests : nosetests]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[tests : nosetests]   File "/workspace/source/service/__init__.py", line 22, in <module>
[tests : nosetests]     from service import routes, models  # noqa: F401 E402
[tests : nosetests]   File "/workspace/source/service/routes.py", line 7, in <module>
[tests : nosetests]     from service.models import Account
[tests : nosetests]   File "/workspace/source/service/models.py", line 12, in <module>
[tests : nosetests]     db = SQLAlchemy()
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
[tests : nosetests]     _include_sqlalchemy(self, query_class)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
[tests : nosetests]     for key in module.__all__:
[tests : nosetests] AttributeError: module 'sqlalchemy' has no attribute '__all__'
[tests : nosetests] 
[tests : nosetests] ======================================================================
[tests : nosetests] ERROR: Failure: AttributeError (module 'sqlalchemy' has no attribute '__all__')
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Traceback (most recent call last):
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
[tests : nosetests]     raise self.exc_val.with_traceback(self.tb)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
[tests : nosetests]     module = self.importer.importFromPath(
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
[tests : nosetests]     return self.importFromDir(dir_path, fqname)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
[tests : nosetests]     mod = load_module(part_fqname, fh, filename, desc)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 234, in load_module
[tests : nosetests]     return load_source(name, filename, file)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 171, in load_source
[tests : nosetests]     module = _load(spec)
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 711, in _load
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[tests : nosetests]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[tests : nosetests]   File "/workspace/source/tests/test_cli_commands.py", line 8, in <module>
[tests : nosetests]     from service.common.cli_commands import db_create
[tests : nosetests]   File "/workspace/source/service/common/cli_commands.py", line 4, in <module>
[tests : nosetests]     from service import app
[tests : nosetests]   File "/workspace/source/service/__init__.py", line 22, in <module>
[tests : nosetests]     from service import routes, models  # noqa: F401 E402
[tests : nosetests]   File "/workspace/source/service/routes.py", line 7, in <module>
[tests : nosetests]     from service.models import Account
[tests : nosetests]   File "/workspace/source/service/models.py", line 12, in <module>
[tests : nosetests]     db = SQLAlchemy()
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
[tests : nosetests]     _include_sqlalchemy(self, query_class)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
[tests : nosetests]     for key in module.__all__:
[tests : nosetests] AttributeError: module 'sqlalchemy' has no attribute '__all__'
[tests : nosetests] -------------------- >> begin captured logging << --------------------
[tests : nosetests] faker.factory: DEBUG: Not in REPL -> leaving logger event level as is.
[tests : nosetests] --------------------- >> end captured logging << ---------------------
[tests : nosetests] 
[tests : nosetests] ======================================================================
[tests : nosetests] ERROR: Failure: AttributeError (module 'sqlalchemy' has no attribute '__all__')
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Traceback (most recent call last):
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
[tests : nosetests]     raise self.exc_val.with_traceback(self.tb)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
[tests : nosetests]     module = self.importer.importFromPath(
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
[tests : nosetests]     return self.importFromDir(dir_path, fqname)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
[tests : nosetests]     mod = load_module(part_fqname, fh, filename, desc)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 234, in load_module
[tests : nosetests]     return load_source(name, filename, file)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 171, in load_source
[tests : nosetests]     module = _load(spec)
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 711, in _load
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[tests : nosetests]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[tests : nosetests]   File "/workspace/source/tests/test_models.py", line 8, in <module>
[tests : nosetests]     from service import app
[tests : nosetests]   File "/workspace/source/service/__init__.py", line 22, in <module>
[tests : nosetests]     from service import routes, models  # noqa: F401 E402
[tests : nosetests]   File "/workspace/source/service/routes.py", line 7, in <module>
[tests : nosetests]     from service.models import Account
[tests : nosetests]   File "/workspace/source/service/models.py", line 12, in <module>
[tests : nosetests]     db = SQLAlchemy()
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
[tests : nosetests]     _include_sqlalchemy(self, query_class)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
[tests : nosetests]     for key in module.__all__:
[tests : nosetests] AttributeError: module 'sqlalchemy' has no attribute '__all__'
[tests : nosetests] 
[tests : nosetests] ======================================================================
[tests : nosetests] ERROR: Failure: AttributeError (module 'sqlalchemy' has no attribute '__all__')
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Traceback (most recent call last):
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
[tests : nosetests]     raise self.exc_val.with_traceback(self.tb)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
[tests : nosetests]     module = self.importer.importFromPath(
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
[tests : nosetests]     return self.importFromDir(dir_path, fqname)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
[tests : nosetests]     mod = load_module(part_fqname, fh, filename, desc)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 234, in load_module
[tests : nosetests]     return load_source(name, filename, file)
[tests : nosetests]   File "/usr/local/lib/python3.9/imp.py", line 171, in load_source
[tests : nosetests]     module = _load(spec)
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 711, in _load
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[tests : nosetests]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[tests : nosetests]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[tests : nosetests]   File "/workspace/source/tests/test_routes.py", line 11, in <module>
[tests : nosetests]     from tests.factories import AccountFactory
[tests : nosetests]   File "/workspace/source/tests/factories.py", line 7, in <module>
[tests : nosetests]     from service.models import Account
[tests : nosetests]   File "/workspace/source/service/__init__.py", line 22, in <module>
[tests : nosetests]     from service import routes, models  # noqa: F401 E402
[tests : nosetests]   File "/workspace/source/service/routes.py", line 7, in <module>
[tests : nosetests]     from service.models import Account
[tests : nosetests]   File "/workspace/source/service/models.py", line 12, in <module>
[tests : nosetests]     db = SQLAlchemy()
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
[tests : nosetests]     _include_sqlalchemy(self, query_class)
[tests : nosetests]   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
[tests : nosetests]     for key in module.__all__:
[tests : nosetests] AttributeError: module 'sqlalchemy' has no attribute '__all__'
[tests : nosetests] 
[tests : nosetests] Name                             Stmts   Miss  Cover   Missing
[tests : nosetests] --------------------------------------------------------------
[tests : nosetests] service/common/__init__.py           0      0   100%
[tests : nosetests] service/common/log_handlers.py      10      8    20%   12-22
[tests : nosetests] service/config.py                   11      5    55%   12-16
[tests : nosetests] --------------------------------------------------------------
[tests : nosetests] TOTAL                               21     13    38%
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Ran 4 tests in 1.222s
[tests : nosetests] 
[tests : nosetests] FAILED (errors=4)
[tests : nosetests] 
